Add a Git alias to push with revision

diff --git a/.config/git/aliases b/.config/git/aliases
--- a/.config/git/aliases
+++ b/.config/git/aliases
@@ -178,6 +178,20 @@ function git:clone:shallow {
   execute_with_echo "git clone --single-branch --depth 1 $*"
 }
 
+function git:push:revision {
+  local revision="$1"
+
+  if [ -z "$revision" ]; then
+    echo "Invalid revision." >&2
+    return 1
+  fi
+
+  local remote="$(git remote show)"
+  local branch="$(git branch --show-current)"
+
+  git push "$remote" "${revision}:refs/heads/${branch}"
+}
+
 function git:clean:bulk {
   local files=( "${(@f)$( git:status:filter:untracked )}" )
 
