Zsh: extract printing messages to functions in my `aws-sso-verify-session`

diff --git a/.config/zsh/bin/aws-sso-verify-session b/.config/zsh/bin/aws-sso-verify-session
--- a/.config/zsh/bin/aws-sso-verify-session
+++ b/.config/zsh/bin/aws-sso-verify-session
@@ -1,6 +1,14 @@
 #!/usr/bin/env zsh
 set -u # Error for unknown variables
 
+function echo:info {
+  printf "\e[0;38;5;6m%s\e[0;0m\n" "INFO -- ${1:?}" >&2
+}
+
+function echo:error {
+  printf "\e[1;38;5;1m%s\e[0;0m\n" "ERROR -- ${1:?}" >&2
+}
+
 profile="${1:?}"
 
 verification_output="$(aws sts get-caller-identity --profile "${profile}" 2>&1)"
@@ -8,10 +16,10 @@ verification_status="$?"
 
 if [ ! "${verification_status}" = "0" ]; then
   if echo "${verification_output}" | rg 'profile.+found' -q; then
-    printf "\e[1;38;5;1m%s\e[0;0m\n" "ERROR -- Profile not found: ${profile}" >&2
+    echo:error "Profile not found: ${profile}"
     return 1
   else
-    printf "\e[1;38;5;6m%s\e[0;0m\n" "INFO -- SSO session is expired. Opening your browser for login..." >&2
+    echo:info "SSO session is expired. Opening your browser for login..."
     aws sso login --sso-session "${AWS_SSO_SESSION_FOR_VERIFICATION:?}" > /dev/null
   fi
 fi
